spring:
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/service-formation/**

          filters:
            - RewritePath=/service-formation/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: FallBabk-formation
                fallbackuri: forward:/defaultFormations

          uri: lb://ms-formation