spring:
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/s-formation/**
          filters:
            - RewritePath=/s-formation/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: fallbck-masformation
                fallbackuri: forward:/defaultFormations
          uri: lb://ms-formation